### ISSUE TITLE
Optimal driving line and pacenotes are drawn during replay playback

### ISSUE THREAD

**Issue by Calinou** [stuntrally/stuntrally#101]
**OS:** Fedora 36
**GPU:** AMD Radeon RX 6900 XT (Mesa driver)
**Stunt Rally version:** 2.7 (Flatpak)

I'm not sure if this is a bug or intended behavior, but unlike other driving aids such as the checkpoint arrow and checkpoint beam, the optimal driving line and pacenotes remain visible during replay playback (unless toggled manually):

![2022-11-13_00 34 53](https://user-images.githubusercontent.com/180032/201498717-dd7c4ca4-fef9-4709-b8c4-082ac6cc78d2.png)

The checkpoint sound also keeps playing during replay playback. I'd expect all driving aids to be turned off automatically when playing a replay.

**Comment by cryham** [comment]
This was intended behavior, I wanted to have all that when making videos from replays, to be similar to real drive.
But I agree there should be an option in Replay - View menu that disables this by default.

**Comment by cryham** [comment]
Ah I see that you have flipper R,G,B colors on HUD Times left top. It should be: Time as sky-blue, Points as orange, Progress red-white. Does it happen anywhere else? Like In GUI tabs, e.g. Track tab is green, Vehicle is red.

**Comment by Calinou** [comment]
> Ah I see that you have flipped R,G,B colors on HUD Times left top. It should be: Time as sky-blue, Points as orange, Progress red-white. Does it happen anywhere else? Like In GUI tabs, e.g. Track tab is green, Vehicle is red.

Indeed, I have this issue on various 2D elements but icons are not affected.
