### ISSUE TITLE
Missing tree textures on Curly Flats map

### ISSUE THREAD

**Issue by AsciiWolf** [stuntrally/stuntrally#102]
Latest Stunt Rally 2.7. It looks like that there are some missing/broken tree textures on the Curly Flats challenge map:

![missing-tree-textures](https://user-images.githubusercontent.com/2339930/201517932-51b802d1-e8ed-4326-b6f4-a098ffff0e11.jpg)

**Comment by cryham** [comment]
Yeah. This is missing triangles. IDK why, and why only recently this happens. It does depend on paged-geom page size. I tested and could change it to some value which in few pages on terrain had vegetation with missing triangles. Probably a bug with paged-geom. IDK. Honestly I'm sick and tired of this ancient piece of software (paged-geom). It will not be used and forgotten in SR3.
I'm not fixing this.

**Comment by cryham** [comment]
Ok fixed in tracks repo, and moved 2.7 tag to it.
