### ISSUE TITLE
Game completely broken for me since update from flathub yesterday

### ISSUE THREAD

**Issue by michael-heerdegen** [stuntrally/stuntrally#105]
Hello,

Yesterday I installed the update coming from flathub.  Before that, the game run quite stable and smooth, and I had quite good graphics.

Now loading any but one track crashes the game (I tried around 20 tracks, and only the first in the tracklist doesn't crash).  The first track "DukeRain" loads and I can drive with the slowest car.  With the default car I get stalls of multiple seconds.  This is with the lowest graphic settings, looking much simpler than that I had been used to in the old version.

I attach the game output (hope I did that correctly).  Please tell me what I can do to provide you with necessary information.

[srl.txt](https://github.com/stuntrally/stuntrally/files/10008326/srl.txt)

**Comment by Calinou** [comment]
Enable **Impostors Only (low quality)** in the vegetation settings to fix stuttering.

**Comment by michael-heerdegen** [comment]
Was one of my first ideas, but not related AFAIU.  I have graphics set to "Lowest" for testing, and that gives me no trees or grass at all.  I know how to cope with stuttering from the old version, and this is a bit different.  The graphics look extremely simple, and first the game runs smoothly, but then out of sudden it freezes for multiple seconds.  Could still be a kind of stutter, but it doesn't feel sane/justified.

My main problem is the crashes, however.  The game is completely unusable.  Sometimes even the settings dialog crashes :-(

**Comment by cryham** [comment]
Hello, from log I see:
Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
GPU Vendor: intel
Device Name: Mesa Intel(R) HD Graphics 4000 (IVB GT2)
It is below SR hardware requirements, and I think it'd be hard to run SR there at all.

There is nothing in log telling why it closed / crased.
I suspect maybe something appears on scene and gets loaded, needs more GPU RAM or resources and that's too much?
You could try setting in game.cfg:
game_freq = 82
this was the old value, now it's 160, could use more CPU but works fine for fast CPUs.
And using car = ES, under car1, has less detail than default HI. Turning off ghost, track ghost, also to reduce GPU resources.

**Comment by cryham** [comment]
Hmm 10% seems like still cleanup so:
does it crash when you load first track in game after start, or next track after any was loaded already?
Can you load only test tracks without road? e.g. TerrainBig, FluidsBig without crashing?
Hard to say what is crashing load. Hope it's not some resources, I think I fixed that.
How is SR editor? Does it also crash?
Does it change anything if you use in game.cfg: `ghost = off`, `trackghost = off`, `grass = 0.000000`, `trees = 0.000000`, `water_reflect = off`, `water_refract = off`, `type = 0` (no shadows).

**Comment by michael-heerdegen** [comment]
Crystal Hammer ***@***.***> writes:

> Hmm 10% seems like still cleanup so:
> does it crash when you load first track in game after start, or next track after any
> was loaded already?

If I understand correctly: whether loading a track crashes or not
doesn't seem to depend on what I did before.  I can load the first track
without problems any number of times.

> Can you load only test tracks without road? e.g. TerrainBig, FluidsBig without
> crashing?

What does "road" exactly mean?  Those tracks are driveable, as are
actually most of these test tracks.  But also "Forks" does work for
example, which I guess has "road".

Not sure what makes the difference.  I can try to make a list of working
and crashing tracks if that would help.

> How is SR editor? Does it also crash?

How again do I start it?

> Does it change anything if you use in game.cfg: ghost = off, trackghost = off,
> grass = 0.000000, trees = 0.000000, water_reflect = off, water_refract =
> off, type = 0 (no shadows).

No.  Everything besides trackghost was already turned off.  I now also
have turned the trackghost off, but that doesn't make a difference.

**Comment by michael-heerdegen** [comment]
Crystal Hammer ***@***.***> writes:

> It could help to locate crashes if you built from sources, but this is rather quite
> difficult recently,
> and did either run ReleaseWithDebug version through gdb like here:
> https://stuntrally.tuxfamily.org/wiki/doku.php?id=troubleshooting
> https://stuntrally.tuxfamily.org/wiki/doku.php?id=compile

Is there a built with debugging symbols available?

For compiling and debugging I would need help.  I can offer giving phone
calls and/or screen sharing via anydesk.  Debian stable here btw.  Am
speaking German and moderately well English.

**Comment by michael-heerdegen** [comment]
Crystal Hammer ***@***.***> writes:

> How is SR editor? Does it also crash?

What I can tell is that I can watch my saved replays.  Replays of tracks
that crash when I try to play them.

And I can watch the "lessons".  All of them.  For me that hints at
something not related to graphics.

**Comment by cryham** [comment]
@AsciiWolf How to start SR editor from flatpak?

**Comment by cryham** [comment]
> If I understand correctly: whether loading a track crashes or not
> doesn't seem to depend on what I did before.  I can load the first track
> without problems any number of times.

Wait so you can load any track, after the game just started?
But loading 2nd track always crashes?
This sounds like my recent issue with resources, but I thought I fixed that.

**Comment by michael-heerdegen** [comment]
Crystal Hammer ***@***.***> writes:

> @AsciiWolf How to start SR editor from flatpak?

/usr/bin/flatpak run --branch=stable --arch=x86_64 \
--command=sr-editor org.tuxfamily.StuntRally

starts the editor for me.  Seems to work ok, no crash.

**Comment by michael-heerdegen** [comment]
Crystal Hammer ***@***.***> writes:

> Wait so you can load any track, after the game just started?

Some do always crash, a few always load.

> But loading 2nd track always crashes?  This sounds like my recent
> issue with resources, but I thought I fixed that.

I guess the replays would then also crash...?

**Comment by AsciiWolf** [comment]
The game runs fine with default graphical preset. Setting some of the graphic settings to a higher values causes Stunt Rally 2.7 to crash. This is a known issue, we were already discussing this several times months ago if I remember correctly. Sadly, there is nothing I can do about this. :-/ This is a Stunt Rally or OGRE issue, not a Flatpak one.

@michael-heerdegen You will sadly most likely have to remove the old `~/.var/app/org.tuxfamily.StuntRally` directory. This will cause all your current settings to be lost, but game should work afterwards.

On the other hand, the old 2.6 Flatpak build was also broken and stuck on the ancient 18.08 Freedesktop runtime + had other problems.

@cryham There should be a desktop entry for the SR editor in your menu created by the Flatpak (using [sr-editor.desktop](https://github.com/stuntrally/stuntrally/blob/master/dist/sr-editor.desktop)).

**Comment by michael-heerdegen** [comment]
Michael Heerdegen ***@***.***> writes:

> I guess the replays would then also crash...?

When loading the track and it crashes, the last thing visible is
"Loading Scene".  Recorded with a screen recorder.

**Comment by michael-heerdegen** [comment]
AsciiWolf ***@***.***> writes:

> @michael-heerdegen You will sadly most likely have to remove the old ~
> /.var/app/org.tuxfamily.StuntRally directory. This will cause all your current
> settings to be lost, but game should work afterwards.

Wow, indeed, everything works now.  All tracks load without crash.  Very
cool.

What can I rescue from the the old directory?  What's the culprit there?

**Comment by cryham** [comment]
Okay I'm thinking this could be due to previous version ghosts/ with old cars (3S,360,CT,M3,TC6, N1,S1), that aren't available now but game finds them and tries to load? Cars are loaded first after clean before loading all stuff on track, this could explain crash at 10-20% percent.
If this is the case, you could you try using whole old user dir, and just renaming / removing `ghost/` dir?
If it works you can try with `ghosts/` but removing only files with any of: 3S,360,CT,M3,TC6, N1,S1 in file name.
For sure `records/` and `replays/` can stay, also `progress*.xml` files can stay.

**Comment by michael-heerdegen** [comment]
Crystal Hammer ***@***.***> writes:

> For sure records/ and replays/ can stay, also progress*.xml files can stay.

It actually seems that deleting only config/stuntrally/game.cfg is
enough to fix the issue.

**Comment by cryham** [comment]
Ah I see.
Kind of strange, we have version in current `game.cfg` and it should have been replaced on 1st run by newer 2.7 version to `game-default.cfg` in game's config dir. Mostly noticable when game changes to small window size on 1st run.
Either way I'm glad it works now.

**Comment by michael-heerdegen** [comment]
Crystal Hammer ***@***.***> writes:

> Ah I see.
> Kind of strange, we have version in current game.cfg and it should have been
> replaced on 1st run by newer 2.7 version to game-default.cfg in game's config
> dir. Mostly noticable when game changes to small window size on 1st run.
> Either way I'm glad it works now.

I now found out that loading the tracks crashes again when I set
graphics down (!) to low.  "medium" works (but is sluggish), and "low"
crashes.  I guess the other way round would make more sense, but that's
how it is.

**Comment by michael-heerdegen** [comment]
Michael Heerdegen ***@***.***> writes:

> I now found out that loading the tracks crashes again when I set
> graphics down (!) to low.  "medium" works (but is sluggish), and "low"
> crashes.  I guess the other way round would make more sense, but that's
> how it is.

So - is it worth it to further investigate?  Maybe not.  I have now
found a setup where the game runs stable and fps are acceptable.  New
tracks are damn cool btw, even with my old hardware.

**Comment by michael-heerdegen** [comment]
Michael Heerdegen ***@***.***> writes:

> So - is it worth it to further investigate?  Maybe not.

Something that also always crashes the game while loading a track is
selecting the "Rhino" car.  Tracks load nearly completely, but
then the game crashes before the scene gets displayed.  All other cars I
tried work normally.  And with Rhino all tracks crash.

**Comment by cryham** [comment]
Strange. Rhino works for me, no idea why.
Well, it's up to you. I guess no need to investigate further.
Could you upload your old game.cfg settings?
I'd compare with default to check if I see anything that would cause this.

**Comment by michael-heerdegen** [comment]
Crystal Hammer ***@***.***> writes:

> Could you upload your old game.cfg settings?  I'd compare with default
> to check if I see anything that would cause this.

It crashes even when I delete my game.cfg.  These are the last output
lines of the game:

| ::: Time Create Hud:  41 ms
| Texture 'waterDepth.png': Loading 1 faces(PF_R8G8B8,1024x1024x1) with 5 hardware generated mipmaps from Image. Internal format is PF_R8G8B8,1024x1024x1.
| /usr/include/c++/12.1.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = CARWHEEL; _Alloc = std::allocator<CARWHEEL>; reference = CARWHEEL&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.

**Comment by michael-heerdegen** [comment]
Crystal Hammer ***@***.***> writes:

> Strange. Rhino works for me, no idea why.
> Well, it's up to you. I guess no need to investigate further.

Yes, this is indeed the final result: after tweaking graphics options I
have a mostly stable game, but Rhino is the only part that is still
crashing reliably.

If there is anything I could try to help to debug this please let me
know.  You saw the assertion violation in the output I had posted?

**Comment by cryham** [comment]
Well it looks like something bad in our code (VDrift actually), like there were no wheels.
But I fear I don't have the time to deal with this. I am very focused now at doing stuntrally3 with new Ogre-Next.

**Comment by cryham** [comment]
multiple-second-long freezes?
I hope it's not vegetation lags, you could try with `trees = 0.000000` in game.cfg. If those freezes are still there, then it is a delay when some new objects appears in view, and then it loads meshes, textures etc.
I have seen these on AkkaPadre and MountCaro, but for me that is like 2 times and 1 or so seconds each.
There is no easy way in Ogre to fix this.

**Comment by michael-heerdegen** [comment]
Crystal Hammer ***@***.***> writes:

> multiple-second-long freezes?
> I hope it's not vegetation lags, you could try with trees = 0.000000 in
> game.cfg. If those freezes are still there,

Seems so, yes.

> then it is a delay when some new objects appears in view, and then it
> loads meshes, textures etc.

That's exactly my gut feeling.

> I have seen these on AkkaPadre and MountCaro, but for me that is like 2
> times and 1 or so seconds each.

Maybe because of the high load the game causes on my system I see it
more often and longer.  MountCaro is indeed one of those tracks where it
is very noticeable after the first 180° turn.

When I enable triplanar and use higher values of anisotropy the effect
happens in more tracks - in this dark winter track for example,
surprisingly, because the track is quite simple and short.  With those
things off it doesn't freeze at all.

> There is no easy way in Ogre to fix this.

Is there maybe an option to load all of that stuff when the track is
loaded, or something to ease loading in-game?


BTW, because my notebook is slow and I tend to get seasick while
playing, I play Turtle most of the time.  I don't find it "turtle speed"
and creepy like - it's nice to enjoy the views and apart from that it
feels much like the car I am driving in real life :-)

**Comment by cryham** [comment]
triplanar and anisotropy use a lot of GPU. It gets worse with integrated GPUs.
The way to fix this (as I also confirmed on Ogre forum) is looking around so it loads all objects etc during loading phase, before game starts.
This is in my todo list.

**Comment by michael-heerdegen** [comment]
Crystal Hammer ***@***.***> writes:

> The way to fix this (as I also confirmed on Ogre forum) is looking
> around so it loads all objects etc during loading phase, before game
> starts.

Ok, thanks for elaborating and your help.  Then...have a nice rest of
your day!
