### ISSUE TITLE
Gamepad recognition

### ISSUE THREAD

**Issue by fgfs-fmanu** [stuntrally/stuntrally#106]
Hello. 

First of all, i would like to thank the developpers for their work developping this game. Il like playing it often.

I have a technical problem on the program. The game has difficulties to recognize my gamepad. I have to lauch it many times before it recognizes it and i have to make all the bindings again before playing.

I'm on Archlinux and my gamepad is a type of Xbox 360. The issue only exists on this game.

Thank you for reading me

**Comment by cryham** [comment]
Hi. Okay.
Could you attach ogre.log (or just console output) for both cases, one when game recognized it, one when it didn't?

**Comment by fgfs-fmanu** [comment]
Solved. The problem was from my side. It was a version installed from snap. Everything works well in the AUR version. Thank you.
