### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [stuntrally/stuntrally#108]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [AnimatedMeshToShapeConverter::getBoneVertices](https://github.com/stuntrally/stuntrally/blob/98aa335c22269c8029f282830878756b5fb905d8/source/btOgre/BtOgreAnim.cpp#L135 "AnimatedMeshToShapeConverter::getBoneVertices function")
- [GrassLoader](https://github.com/stuntrally/stuntrally/blob/70bd898df76d1f8023ce100b9128de60d355c091/source/paged-geom/GrassLoader.cpp#L72 "Destructor for GrassLoader")

**Comment by cryham** [comment]
not used in SR3
