### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by fgfs-fmanu** [stuntrally/stuntrally#110]
Hello. I would like to report an issue i have on the game.

Sometimes, Stuntrally make no sound to the speakers.  This behavior is random. Some days i have sound, some days not.  I update my system often.

I send the log, but the issue is not mentioned in the log. The issue appears in the terminal: 

`@  ---- Sound devices ----
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.rear.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM rear
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
@  ALSA Default
@  HDA Intel PCH [ALC892 Analog] (hw:0,0) via ALSA
@  HDA Intel PCH [ALC892 Digital] (hw:0,1) via ALSA
@  HDA NVidia [HDMI 0] (hw:1,3) via ALSA
@  HDA NVidia [HDMI 1] (hw:1,7) via ALSA
@  HDA NVidia [HDMI 2] (hw:1,8) via ALSA
@  HDA NVidia [HDMI 3] (hw:1,9) via ALSA
@  HDA NVidia [HDMI 4] (hw:1,10) via ALSA
@  HDA NVidia [HDMI 5] (hw:1,11) via ALSA
@  C-Media CMI8738 [C-Media PCI DAC/ADC] (hw:2,0) via ALSA
@  C-Media CMI8738 [C-Media PCI 2nd DAC] (hw:2,1) via ALSA
@  C-Media CMI8738 [C-Media PCI IEC958] (hw:2,2) via ALSA
@  PortAudio Default
@  No Output
@  EFX extension found.
@ @  ---- SoundManager Info ----
@  vendor: OpenAL Community
@  version: 1.1 ALSOFT 1.13
@  renderer: OpenAL Soft
@  extensions: AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_sub_data AL_SOFT_loop_points
@  Aux Sends per Source: 4
@  SoundScript: Sound Manager started with 0 sources
@  SoundScript: Parsing
@  SoundScript: Parsed: 44 templates.
::: Time Sounds: 345 ms
@  Sound init ok.
`

Here's the orge.log file: [ogre.log](https://github.com/stuntrally/stuntrally/files/10229704/ogre.log)

Maybe i made a mistake configuring the sound. The sound works well in the other apps.

I'm on Archlinux. My version of Stuntrally is 2.6-1

A detail:  i use a pci sound card. The card on my motherboard does not work.

Thank you for your help.

**Comment by Calinou** [comment]
Can you reproduce this issue on the [Stunt Rally 2.7 Flatpak](https://flathub.org/apps/details/org.tuxfamily.StuntRally)?

**Comment by fgfs-fmanu** [comment]
Hello. Works great with Flatpak. Thank you!
