### ISSUE TITLE
I miss the S1 :cry: 

### ISSUE THREAD

**Issue by ThibaultLemaire** [stuntrally/stuntrally#120]
Hey, so, I noticed you dropped some cars with v2.7 and I was wondering why?

(I love the S1, it has better accel than the ES, making it better on curvy tracks. Maybe I just had a better feel for it than for the ES, but many challenges became much easier with the S1.)

**Comment by cryham** [comment]
It was due to this:
https://forum.freegamedev.net/viewtopic.php?f=81&t=18532
I missed it a bit too, but I'm now driving SX instead.

**Comment by ThibaultLemaire** [comment]
Licensing, I see, I was afraid that'd be it. Thanks.

SX is great but it's asphalt, so I can't 'cheat' the gravel challenges with it ;)
