### ISSUE TITLE
Please make an appimage version of your app

### ISSUE THREAD

**Issue by Brensom** [stuntrally/stuntrally#144]
Please make an appimage version of your app

**Comment by Calinou** [comment]
There's already a Flatpak: https://flathub.org/apps/org.tuxfamily.StuntRally

I wouldn't bother creating an AppImage as it doesn't bring any noticeable benefits over a Flatpak for our use cases. Maintaining an AppImage is significantly more involved than a Flatpak, as it's more likely to break on various distributions.
