### ISSUE TITLE
Vsync is always on (with Ogre 1.11)

### ISSUE THREAD

**Issue by AsciiWolf** [stuntrally/stuntrally#27]
https://github.com/stuntrally/stuntrally/pull/23#issuecomment-772486797

(Just to make it clear that there is this issue with current master code. :-))

**Comment by cryham** [comment]
But works okay when built with Ogre 1.9. At least from Debian repos.

**Comment by AsciiWolf** [comment]
Ah. I was testing it only with OGRE 1.12.10 and latest Stunt Rally from Git.

**Comment by cryham** [comment]
Not happening with recent 1.13, closing.
