### ISSUE TITLE
Vertex explosions caused by trees

### ISSUE THREAD

**Issue by AsciiWolf** [stuntrally/stuntrally#28]
I have built an updated Stunt Rally Flatpak for Linux using latest master code and OGRE 1.12.11. However, on some maps (for example Curly and Rocky), there are weird vertex explosion glitches displayed:

![glitches](https://user-images.githubusercontent.com/2339930/107885188-1dc08380-6ef9-11eb-93ce-cd140c8b4a38.png)

It seems that they are caused by trees. If I change the tree density setting to a minimal level, these glitches disappear. And they only seem to happen when the game graphical details are set to high (or higher).

It does not happen with older (stable 2.6.1) Stunt Rally version (that was using older OGRE), even when using the same Flatpak runtime (with same GPU drivers etc.). I am using an onboard Intel graphic.

By the way, game also occasionally crashes during track loading, but it may be a different issue (however I was not able to find anything useful in logs).

**Comment by paroj** [comment]
this does not happen when combining StuntRally master with OGRE 1.9, so I guess the following patch is incomplete:
https://github.com/OGRECave/ogre-pagedgeometry/commit/7c9295f771e8c7973efc04d53283978ccd44fc9b

**Comment by AsciiWolf** [comment]
@paroj Could you prepare a fix? I am not so skilled in C++ and have no deeper knowledge of OGRE to do it myself.

**Comment by AsciiWolf** [comment]
@paroj Could you prepare a fix? I am not so skilled in C++ and have no deeper knowledge of OGRE to do it myself.

**Comment by AsciiWolf** [comment]
@paroj Any news? I would love to update [my Flatpak](https://flathub.org/apps/details/org.tuxfamily.StuntRally), but this is a blocker. :-/

**Comment by paroj** [comment]
I am currently short on time. However, you could help out by finding out which .mesh file is causing this (clearly the trees in the background are not affected).

The meshes are located in the trees*/ subdir here:
https://github.com/stuntrally/stuntrally/tree/master/data

you can use ogre-meshviewer to open the files:
https://github.com/OGRECave/ogre-meshviewer

to test whether you got the right .mesh you can rename it and replace it by copying .mesh that is working.

**Comment by AsciiWolf** [comment]
Is there any easy way to compile/install the Mesh Viewer on a Linux distribution that does not use Snap? I unfortunately do not have Snap on any of my systems, only Flatpak and regular packages.

**Comment by paroj** [comment]
if your distribution packages python (e.g. python3-ogre-1.12 on debian), checking out the repo should be sufficient.

Otherwise see: https://snapcraft.io/docs/installing-snapd

**Comment by AsciiWolf** [comment]
Thanks, I will try building and bundling ogre-meshviewer as a part of the WIP [Flatpak PR](https://github.com/flathub/org.tuxfamily.StuntRally/pull/7) when I have some time. :)

**Comment by cryham** [comment]
> which .mesh file is causing this and which are not (clearly the trees in the background are not affected).
> 
Those in background are impostors (just 2D billboards from texture). Lower graphics setting use impostors, not meshes IIRC so it won't happen there too.
For me this looks like some issue with wind shader for vegetation models?

Curly and Rocky tracks have many of the old Ogre provided trees:
/bin/data/trees-old/tree.07.mesh and tree.09.mesh (you could change them in editor to other, to see if this is their mesh problem? I see it has MeshSerializer_v1.8 used inside like others do. So maybe it is a problem with mesh scale? IIRC newer models were smaller (still shouldn't matter).

If it doesn't happen with low tree density then maybe GPU memory? I'm guessing.

**Comment by AsciiWolf** [comment]
![editor_flooded](https://user-images.githubusercontent.com/2339930/111009144-18891400-8393-11eb-852a-3d71b3f313ec.png)

This is how one of the problematic maps looks like in SR Editor. To be honest, I am not sure how to work with the editor, but I will try and will let you know whether I made any progress. :-)

**Comment by AsciiWolf** [comment]
Well, I pressed some button (not sure which one) and this happened along with an "unloading impostors" message on stdout:

![editor_flooded_no_impostors](https://user-images.githubusercontent.com/2339930/111009558-3c008e80-8394-11eb-9de7-c83a6840d14b.png)

Map now looks correct (except that there are no trees). However, this is not much useful, right? :-)

**Comment by AsciiWolf** [comment]
I have noticed another smaller glitch when moving the camera:

![editor_flooded_glitch](https://user-images.githubusercontent.com/2339930/111009984-70c11580-8395-11eb-8410-833745fe694c.png)

However, it seems to happen only in the SR Editor, not in actual game.

I will try playing with the editor more during this weekend...

**Comment by cryham** [comment]
You pressed V it toggles visibility of vegetation.
There is some info about vegetation in editor here (newest version)
https://cryham.tuxfamily.org/portfolio/2015-sr-track-editor/10/
and a very old tutorial video
https://www.youtube.com/watch?v=L6eZKLG79TQ
I'm curious if this happens with any vegetation models even the newer trees (e.g. for autumn)? If so then it's not .mesh files problem but paged-geom or Ogre or shaders regarding wind for vegetation models or such.

**Comment by AsciiWolf** [comment]
Autumn seems to have the same issue:

![editor_autumn](https://user-images.githubusercontent.com/2339930/111043790-cc96a780-8444-11eb-8d9d-6cd29aa4ac05.png)

**Comment by cryham** [comment]
Okay. Can you test by disabling wind?
This is done in vegetation model (for the tree that we see exploding) and set .wind Fx and .wind Fy to 0.000 and then press Update. Does it still look so bad after or is normal?

**Comment by AsciiWolf** [comment]
I have tried setting .wind Fx and .wind Fy to 0.000 for all (5) used vegetation models, but no luck, still the same problem. :-/

**Comment by cryham** [comment]
Hmm I got another idea to test.
Can you hide vegetation with V and got to Vegetation Models tab, does the preview area (for this exploding tree) show the tree normally or is it exploding or nothing there?
The preview area on right bottom normally shows a rotating view for model (tree) without wind.

**Comment by AsciiWolf** [comment]
It shows the tree normally.

**Comment by AsciiWolf** [comment]
I just noticed that even rocks, not just trees, seem to have this issue:

![editor_flooded_rocks](https://user-images.githubusercontent.com/2339930/111078378-6027b100-84f5-11eb-9e97-24f8bc399cf9.png)

**Comment by cryham** [comment]
Hah okay. So this is something directly from paged-geom and its geometry batching that messes it up.
Perhaps you could try other values (smaller or bigger) for Vegetation models Page size?
But I don't really know its code, now it could be time to look into it to see what happens. I don't have the time at all recently.
The preview model doesn't use paged-geom, it is just using Ogre to view mesh. I think shaders are the same? Or at least generated from same code. Maybe this shader fragment with wind goes bad? I don't know.
So, this didn't happen in previous flatpack SR with Ogre version 1.9? Then perhaps something in Ogre changed?

**Comment by paroj** [comment]
do you also get the errors with ogre 1.12.10?

**Comment by AsciiWolf** [comment]
Wow, it seems to work fine with 1.12.10! Anyway, I have noticed another (major) issues (not related to this one) and will create separate tickets for them.
