### ISSUE TITLE
Lot of stuttering during gameplay (paged-geom vegetation lags)

### ISSUE THREAD

**Issue by AsciiWolf** [stuntrally/stuntrally#31]
When using latest Stunt Rally from Git with OGRE 1.12.10, there seems to be lot of stuttering during the gameplay. It seems to probably be caused by vegetation models because it does not happen on maps with minimal vegetation. If I remember correctly, there was no such issue with older Stunt Rally / older OGRE.

**Comment by cryham** [comment]
Is this something new or the issue we had with paged-geom loading pages for very long causing delays when moving? https://github.com/OGRECave/ogre-pagedgeometry/issues/12

**Comment by AsciiWolf** [comment]
Hmm, I am not sure. But I was not experiencing this issue when using older Stunt Rally 2.6.1 + OGRE 1.9.

**Comment by cryham** [comment]
Well that issue was not happening in Ogre 1.9, only in later but should be fixed in latest Ogre.

**Comment by Calinou** [comment]
> It looks like that it stutters more on maps with a lot of vegetation.

Does stuttering get better if you enable **Impostors Only (low quality)** in the vegetation settings?

**Comment by AnotherFoxGuy** [comment]
I encountered the same issue on windows, the only way to fix it is by disabling pagedgeometry

**Comment by AsciiWolf** [comment]
It does! In fact, all stuttering is gone now after enabling Impostors Only. :-)

By the way, I have noticed small glitches when "Impostors Only" are enabled:

[stuntrally_vegetation_glitch.webm](https://user-images.githubusercontent.com/2339930/189979192-1048398a-2af1-4628-b8a9-ad3d386f1d1c.webm)

**Comment by Calinou** [comment]
> It does! In fact, all stuttering is gone now after enabling Impostors Only. :-)

@cryham This makes me think that setting should be enabled by default, as I've found it helps a lot with running the game on lower-end machines.

I know it looks kind of ugly when up close, but maybe we can increase the impostor resolution and decrease the number of Y variants generated to keep memory usage to a similar level as before.

**Comment by AnotherFoxGuy** [comment]
I think this is an issue with the forked version of paged, since RoR also uses paged and we don't have any issues with stuttering/framedrops

**Comment by AsciiWolf** [comment]
Hmm, is there something I could try doing on my end to fix it (without using impostors only)?

**Comment by cryham** [comment]
"Impostors Only should be enabled by default"
OMG no. They look hideous, would make default game look further 10 years back I guess.

Yeah I know, the 2 main performance killers in SR are:
- paged-geom performance (on CPU) instead of HW Instancing, which is present in Ogre (has nice demo too) and we could use it (IDK how to deal with this in shiny's materials)
- shadows, IDK if could improve that, but surely could look better with CSM, which is also present in Ogre

We need programmers. I can't really deal with all of this myself, especially nowadays.
And I'd really like a lot more to move to Ogre-next (2.3 or 3.0 IDK) and just throw out paged-geom into ocean with maniacal laugh. But yeah, impostors may probably be still needed there too.

**Comment by cryham** [comment]
@AnotherFoxGuy interesting. Maybe because there is (a lot) less vegetation in RoR, or only 1-2 models? I don't think anything critical changed, it is still using CPU to create batched geometry (for each vertex).

**Comment by AnotherFoxGuy** [comment]
> Maybe because there is (a lot) less vegetation in RoR, or only 1-2 models?

It depends on the map, but there are some maps with quite some vegetation that run 60fps without any framedrops

![image](https://user-images.githubusercontent.com/9480940/190271131-136f7ae5-f5a5-4903-a1ee-c7e143b768b9.png)

**Comment by AsciiWolf** [comment]
Even Stunt Rally used to run pretty solid with just minor stuttering when using older Stunt Rally build (2.6.1) + old OGRE.

**Comment by cryham** [comment]
@AnotherFoxGuy 
This is interesting. Wow, 1420 batches and 60 FPS? I can't even. In SR 500 batches is already big, and it drops from 60 FPS quickly to low fps. Was before and even with my AMD RX 570 is now I'd say.
But still on this RoR screen I see like 1 or 2 pine models. What material system is this? RTSS or just basic .material? I think our shiny materials do matter here, I mean drop FPS but look better. But IDK how much. I remember once seeing few million triangles of vegetation with smooth FPS but without shaders and shadows at all. Once I added them back FPS was go dead low as usual.

@AsciiWolf 
I don't really know what to do with it. I mean nothing has changed in paged-geom code or in SR for vegetation. Only Ogre is newer.
Just to make sure: is this Release, ReleaseWithDebug or Debug? I do have those delays (lag) in Debug but I don't in ReleaseWithDebug and surely not in Release. Those are probably CPU times when creating vegetation batch pages.
Perhaps page sizes changed IDK, those are track settings.

**Comment by AsciiWolf** [comment]
My CPU changet to a much newer/faster one (Haswell generation Xeon E3 vs Ryzen 5 5600X). Hmm, good question about the release type. I thought that it is "ReleaseWithDebug", but I am not so sure now. I will try manually specifying "ReleaseWithDebug" as the release type. Thanks for the tip! :-)

**Comment by AsciiWolf** [comment]
Setting "`-DCMAKE_BUILD_TYPE=RelWithDebInfo`" did nothing, however it looks like that "`-DCMAKE_BUILD_TYPE=Release`" has resolved the issue. :-) There is still stuttering on some maps (especially on Curly and Hilly), but it is not that serious now and game is still fully playable.

**Comment by cryham** [comment]
Okay great.
Curly and Hilly, sounds like some small page size, but yeah small pages make shorter lags more frequently and bigger page will make long delays but less often.

**Comment by cryham** [comment]
Interesting I don't have lags on Debian with ReleaseWithDebug and I have older CPU i7 2600K (OC-ed but still like 10 years now).
All SR Windows release installers had always Release. Won't probably see callstack only info is ogre.log.

**Comment by cryham** [comment]
Maybe RoR is using HW instancing?
Anyway since this was fixed with Release build, I'm closing.
I'll change in 2.7, under [ sim ] in game.cfg, game_freq value to 160.0. It makes SR smoother, well lags are still there, so besides the lags.
[stuntrally3](https://github.com/stuntrally/stuntrally3) will not have any (vegetation) lags, paged-geom will not be used (or remembered even).

**Comment by cryham** [comment]
Right. Autumn and its start place has a lot of trees. So its paged-geom again.
I won't be dealing with this though. Old Ogre does have HW instancing which would fix this, but we use shiny for shaders nor RTSS, so it's not trivial to adapt, while also still using impostors? We don't have vegetation .mesh files with LOD most likely either.
Either way, I'm more into stuntrally3 for fixing this, as it will bring more cool features (effects, lights, PBR etc), but still lots to do to get anywhere near that.
