### ISSUE TITLE
Missing releases

### ISSUE THREAD

**Issue by jhonny-oliveira** [stuntrally/stuntrally#40]
Hi!

It seems the latest releases went missing (release tab), could you please recreate them? I'm packaging stuntrally for Ubuntu and my watch file relies on the releases to detect new versions. I need at least the last release.

Thank you!
Jhonny Oliveira
https://xtradeb.net

**Comment by AsciiWolf** [comment]
There are tags: https://github.com/stuntrally/stuntrally/tags

**Comment by jhonny-oliveira** [comment]
Something changed, because there were a couple o repos I was watching in Github that had their releases vanishing around the same time in October. The most frequent answer I got from the repo owners was that they never created them in the first place. I guess, these were created automatically and Github decided to turn them off.

Anyways, thank you for answering and for the good work with Stuntrally! Stay strong!
