### ISSUE TITLE
HUD elements are missing when using 4k screen resolution

### ISSUE THREAD

**Issue by scratchifoo** [stuntrally/stuntrally#42]
Hello,

When setting the screen resolution to 3840x2160; which is the native resolution for my display, the digital speedometer, gear indicator, boost level and damage level are not display; but the analog speedometer and tachometer work fine.  When setting lower resolutions, those elements are there and work as expected.

Just to clarify, here are a couple of screenshots comparing 3840x2160 to 2560x1440 (which works fine).
3840x2160 bug : https://slavabox1.planetslav.ca/index.php/s/98HXSjcGZBYTkRq?dir=undefined&openfile=276431
2560x1440 good: https://slavabox1.planetslav.ca/index.php/s/98HXSjcGZBYTkRq?dir=undefined&openfile=276440

Also, the Lap Results in the top right are missing as well.  Other than this glitch, everything else in the game works fine at 4k.  Any ideas if this is an easy fix and where one should look to fix it?  Any advice appreciated.

Thank you

**Comment by cryham** [comment]
Should be fixed now, on master.

**Comment by scratchifoo** [comment]
It works now, thank you so much!
