### ISSUE TITLE
Last stable version Bullet?

### ISSUE THREAD

**Issue by DJs3000** [stuntrally/stuntrally#47]
It is possible to use the latest version of the physics engine. I use 3.21 Bullet version(SHARED LIBS=ON). Bullet github repository, has the earliest version 2.82. I've tried different versions to build, but stuntrally never sees bullet.

![image](https://user-images.githubusercontent.com/16526540/154873324-ba594c03-ad82-4eb7-8efa-74c1354afb86.png)

**Comment by cryham** [comment]
I'm not sure.
But since we started using Conan to build, there is bullet3 / 3.24 version set inside `cmake/DependenciesConfig.cmake`
Closing, reopen if needed.
