### ISSUE TITLE
Describe what difficulty levels do on the main menu

### ISSUE THREAD

**Issue by Calinou** [stuntrally/stuntrally#52]
One of my pet peeves in gaming is difficulty levels that don't describe what they do. Knowing in advance *what* the difficulty level setting changes can make a big difference in choosing the right skill level for yourself.

Unfortunately, Stunt Rally https://github.com/stuntrally/stuntrally/commit/cb9adab7039c82d23e7057df7a4dcd85038bb8be is currently a victim of this:

![image](https://user-images.githubusercontent.com/180032/170837165-cc7be6c2-7e9d-4924-88e6-80b53c164d1d.png)

This could be done by adding a line below the difficulty setting, which changes depending on the difficulty setting. Quick mockup:

![image](https://user-images.githubusercontent.com/180032/170837228-15e9089e-d48f-44aa-af8e-9dcb3ad3a024.png)

PS: I'm very happy to see Stunt Rally is making a comeback :smile:

**Comment by cryham** [comment]
Right. Can I just put the line from changelog
Game difficulty combo, changes: HUD, tracks filter, game setup, default track and vehicle
into standard tooltip?
I was thinking of adding a 2nd combo there, for just simulation difficulty (easy, normal, and future hard). To make it separate.

**Comment by Calinou** [comment]
> Can I just put the line from changelog
> Game difficulty combo, changes: HUD, tracks filter, game setup, default track and vehicle
> into standard tooltip?

I think this is a good start, but ideally, the tooltip should change depending on the currently chosen difficulty level. It's important to be able to compare difficulty levels between each other as well.

**Comment by cryham** [comment]
How about both Game difficulty and Simulation mode combos in main menu with an icon [?] on right that will show in tooltip the details of what changes?
