### ISSUE TITLE
Add near-infinite water planes in more tracks to make the terrain size limit less noticeable

### ISSUE THREAD

**Issue by Calinou** [stuntrally/stuntrally#56]
Some tracks such as Isl6-Flooded use a near-infinite water plane. It helps hide the fact that the terrain plane is finite, and makes the scenery feel a lot more cohesive.

Not all tracks which have a sea/ocean/lake do this though. It might be worth doing a pass on all tracks and add large water planes to those tracks. Performance will probably be slightly worse as a result, but it can result in a big upgrade to ovearll visual quality.

As a bonus, there could also be a way to add solid planes with terrain textures for tracks that don't have large spans of water. These solid planes could be made to extend outside the playable area, and give the impression of a larger terrain. This could be especially effective in desert or snowy sceneries. (This might be worth splitting to its own issue.)

**Comment by cryham** [comment]
I don't want this. It's not a replacement for horizons. It'd make tracks feel like islands.
Then fog and its mismatch will be more visible on water. Also would slightly require more GPU to render.

**Comment by cryham** [comment]
Horizons are on todo already https://stuntrally.tuxfamily.org/mantis/view.php?id=11 kind of lot to do, so no progress or priority.
