### ISSUE TITLE
R in new logo doesn't look like R

### ISSUE THREAD

**Issue by Tarek-Hasan** [stuntrally/stuntrally#68]
Hi @cryham,
Thanks for your effort to bringing this old project back to life. I noticed in the new logo update, the R in SR doesn't look like R. So I'm here presenting some idea about it.

![R curved upward](https://user-images.githubusercontent.com/27731012/178095385-2597578c-be1c-4fc2-8d39-56e6c533efe6.png)
![R curved downward](https://user-images.githubusercontent.com/27731012/178095383-15185f01-c0bf-4c82-af2c-3674cae1d741.png)
![R straight end](https://user-images.githubusercontent.com/27731012/178095386-5ae99ef0-995e-4bac-935c-30d15114876a.png)
![curved r](https://user-images.githubusercontent.com/27731012/178095381-2f0ce482-3080-4ff6-8bf0-4d3748e2fac6.png)

I also liked this R design I found online:
![vector curved R](https://user-images.githubusercontent.com/27731012/178095474-838cb9df-dfce-4dd5-8967-0eb986fff277.png)

**Comment by cryham** [comment]
![](https://github.com/stuntrally/stuntrally/blob/master/data/gui/stuntrally.png?raw=true)
Not an issue, closing
First of all it is easy to drive, it's pipe road after all. I don't see any problems with shape, looks like R. And lastly I just did logo and icons, I'm not doing that again in like 5 years.
Your first 3 Rs have very sharp corner. Next doesn't look like R, last looks okay but doesn't matter.
