### ISSUE TITLE
Changing language in "Help" window causes the game to crash

### ISSUE THREAD

**Issue by AsciiWolf** [stuntrally/stuntrally#86]
Stunt Rally crashes at most times when changing the game language in "Help" window with latest Stunt Rally from Git (5ce6dde7273e61bf504e4b60bd288bfeac3a8ecb + https://github.com/stuntrally/tracks/commit/bef80ff5cdec845c3d04b7066c7d96eb025332db) + latest OGRE (13.4.4) on x86_64 Linux.

**Comment by cryham** [comment]
yeah I think I'll just make it ** needs restart, like like in SR editor, has same problem

**Comment by cryham** [comment]
yeah, not really fixed
