### ISSUE TITLE
Pressing "F12" causes the game to immediately close

### ISSUE THREAD

**Issue by AsciiWolf** [stuntrally/stuntrally#89]
Stunt Rally 58bd82c5f98f7f16afe93ee59c5ec07ac555c602 from Git. I am not sure whether this is intentional, but pressing "F12" immediately closes the game without any warning. There is no crash or errors in the game log.

**Comment by cryham** [comment]
Yes screenshot won't save jpg now in Ogre 1.13. It works with png (screenshot_png = on) only.
I think something wrong with library /usr/local/lib/OGRE/Codec_STBI or needs another plugin.

**Comment by Calinou** [comment]
Enabling PNG screenshots by default would resolve this. I don't think JPEG screenshots should be a thing anymore in 2022 (not by default at least) :slightly_smiling_face:
