### ISSUE TITLE
Unable to build Stuntrally 2.7 on Ubuntu 22.04

### ISSUE THREAD

**Issue by jhonny-oliveira** [stuntrally/stuntrally#98]
Dear @cryham,

I'm attempting to build Stuntrally in Ubuntu 22.04 without success. I get and error related to Ogre.

As per your instructions I also built Ogre *13* but I'm not sure if it is the correct version. Can you please specify the exact download URL?

I used this version/recipe of Ogre: https://salsa.debian.org/games-team/ogre/-/tree/ogre-13.3 which in turn is using this source version: https://github.com/OGRECave/ogre/releases/tag/v13.3.2.

Thank you!
Jhonny Oliveira
https://xtradeb.net

**Comment by cryham** [comment]
Well yes, Ogre from that github url will be good, even latest I'd say because there is a fix 4 days ago related to terrain in SR editor.
https://github.com/OGRECave/ogre/commits/master
I've built on my Debian 11, just using CMake, but keep in mind forget we need to set:
OGRE_RESOURCEMANGER_STRICT 0
OGRE_NODELESS_POSITIONING ON
Here is a guide for building Ogre from sources:
https://ogrecave.github.io/ogre/api/1.12/building-ogre.html

**Comment by jhonny-oliveira** [comment]
Dear @cryham,

I managed to successfully build StuntRally 2.7. However, the process present some serious challenges. Please, find the steps I took below.

1. I packaged [Ogre 13.3.2](https://github.com/OGRECave/ogre/releases/tag/v13.3.2) based on [Debian Ogre 13.3.2](https://salsa.debian.org/games-team/ogre/-/tree/ogre-13.3/). Unfortunately, SR 2.7 requires the latest Ogre.
2. So, I update the Debian Ogre package and packaged [Ogre 13.5.1](https://github.com/OGRECave/ogre/releases/tag/v13.5.1). However, this version requires imgui 1.87.
3. So, I also packaged imgui 1.87, because Ubuntu only has [imgui 1.86](https://salsa.debian.org/yangfl-guest/imgui), at the moment.

Although, I had to build two additional packages and this is already cumbersome enough, this is the least of my problems. The package recipe for Ogre 13.3.2+ conflicts with all previous distribution versions: libogre-1.8-dev, libogre-1.9-dev, libogre-1.12-dev. Meaning, that if I release this under [XtraDeb](https://xtradeb.net) I will break every other app or game that depends on those versions.

As you can imagine, at this point I'm a bit stuck. Would it be possible to stick to one Debian official release that doesn't conflict with any other previous version and without any tweaking (OGRE_RESOURCEMANGER_STRICT, OGRE_NODELESS_POSITIONING - in case these cause any additional conflicts)? Could we use Ogre 1.12.10? As I mentioned [here](https://github.com/stuntrally/stuntrally/issues/49#issuecomment-1272302856), I previously managed to successfully built it there. Is there anyway you can at least help me patch it back to Ogre 1.12.10?

Thank you!

**Comment by cryham** [comment]
I see. Looks indeed too complicated.
Anyways a question, is this all required for SR only, or will there also be the same problems with just packaging Ogre 13.5.1 or newer in latest Debian?

I'll ask @paroj, is imgui needed for Ogre 13.5.1 to build now? Or is it optional, but on by so by default? So would it require another CMAKE variable?

**Comment by jhonny-oliveira** [comment]
As it is now, the main problem concerns the current Ogre 13.5.1 packaging recipe. Maybe it could be packaged in a non conflicting way, but this presents two issues: it might be behind may skills with reasonable amount of effort and I really don't want to deviate from the main Debian Ogre packaging team as it might cause further issues down the stream.

This is the error with Ogre 1.12.10:

`/<<PKGBUILDDIR>>/source/ogre/common/Terrain.cpp:205:43: error: ‘class Ogre::TerrainGroup’ has no member named ‘getTerrainSlots’; did you mean ‘getTerrainSlot’?
  205 |                 auto tsm = mTerrainGroup->getTerrainSlots();
      |                                           ^~~~~~~~~~~~~~~
      |                                           getTerrainSlot
`

You can find the full build log here: [build_log.txt](https://github.com/stuntrally/stuntrally/files/10000772/build_log.txt).

About the imgui dependency, I wouldn't pursue it any further. If that was the main problem, I wouldn't mind packaging it. Actually, at this point, it is only a matter of publishing it.

**Comment by paroj** [comment]
> The package recipe for Ogre 13.3.2+ conflicts with all previous distribution versions: libogre-1.8-dev, libogre-1.9-dev, libogre-1.12-dev. 

while you can only install one -dev variant, it is perfectly fine to have libogre-1.12 and libogre-13 installed at the same time

**Comment by jhonny-oliveira** [comment]
> > The package recipe for Ogre 13.3.2+ conflicts with all previous distribution versions: libogre-1.8-dev, libogre-1.9-dev, libogre-1.12-dev.
> 
> while you can only install one -dev variant, it is perfectly fine to have libogre-1.12 and libogre-13 installed at the same time

You are right about the libogre-*-dev, unfortunately, the package definition ([Ogre 13.3.2](https://salsa.debian.org/games-team/ogre/-/blob/ogre-13.3/debian/control)) also states the following:

Package: libogremain13.3
Breaks: libogre-13.3 (<<1.12.10+dfsg2-3)
Replaces: libogre-13.3 (<<1.12.10+dfsg2-3)

I assume this was done for good reason.

**Comment by jhonny-oliveira** [comment]
> This is the error with Ogre 1.12.10

Dear @cryham ,

did you have a look at my previous reply? Is there any chance we can make the code work with Ogre 1.12.10.

For two year that I'm unable to package Stuntrally. It would be a nice holiday present to the community if I could.

Thank you!

**Comment by paroj** [comment]
> I assume this was done for good reason.

probably because libogre also contains the media files, that are installed into a unversioned directory. However, this is easily fixable by specifying a versioned OGRE_MEDIA_PATH.

**Comment by cryham** [comment]
@jhonny-oliveira Yes I saw it back then, I will try to fix this soon. I'm just very busy with [stuntrally3](https://github.com/stuntrally/stuntrally3)

**Comment by cryham** [comment]
@jhonny-oliveira Can you try building? That getTerrainSlots should be fixed, no idea if something else still needs ogre version check.

**Comment by jhonny-oliveira** [comment]
Thank you @cryham! Built and published: https://xtradeb.net/play/stuntrally/#comment-433 .
The game is playable, but the car looks a bit funny, thought. The wheels and some other parts are white (default car). The game still core dumps when I exit it. Anyways, I think this is out of the scope of this request. Fell free to close it.

@paroj, see below the overlapping package/files. libogre-13.5-dev is fine. You should either develop with one or the other. The other two are not. Handling it is a bit above my skills. :-) Eventually, the debian team will sort it out.

libogre-13.5-dev
 /usr/include/OGRE
 /usr/lib/x86_64-linux-gnu/OGRE
 /usr/lib/x86_64-linux-gnu/pkgconfig/OGRE*
 /usr/lib/x86_64-linux-gnu/libOgre*

ogre-13.5-tools
 /usr/bin/Ogre*
 /usr/bin/VRMLConverter
 /usr/share/man/man1/Ogre*
 /usr/share/man/man1/VRMLConverter.1.gz
 
python3-ogre-13.5
 /usr/lib/python3/dist-packages/Ogre/

**Comment by cryham** [comment]
Okay, closing.
